---
name: "GDUnit4 Unit Tests"

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: "Codecov requires a token to authenticate"
        required: true

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      checks: write
    steps:
      - uses: "actions/checkout@v6.0.1"
      - name: "Download Godot Binary"
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          unzip Godot_v4.5-stable_linux.x86_64.zip
          mv Godot_v4.5-stable_linux.x86_64 godot
          chmod +x godot
      - name: "Install GDUnit4"
        run: |
          mkdir -p addons
          wget https://github.com/MikeSchulze/gdUnit4/archive/refs/tags/v6.0.0.zip
          unzip v6.0.0.zip -d addons
          mv addons/gdUnit4-6.0.0/addons/gdUnit4 addons/gdUnit4
          rm -rf addons/gdUnit4-6.0.0
      - name: "Import Resources"
        run: |
          ./godot --headless --path . --import --quit
      - name: "Run GDUnit4 Tests"
        run: |
          ./godot --headless --path . -s res://addons/gdUnit4/bin/GdUnitCmdTool.gd \
            --verbose \
            --ignoreHeadlessMode \
            --add res://test
      - name: "Find Latest Report Directory"
        id: find_report
        run: |
          LATEST_REPORT=$(ls -td reports/report_* | head -1 || echo "")
          if [ -z "$LATEST_REPORT" ]; then
            echo "No report directory found; tests may not have generated reports."
            exit 1
          fi
          echo "latest_report=$LATEST_REPORT" >> $GITHUB_OUTPUT
      - name: "List Coverage Reports"
        run: |
          ls -la ${{ steps.find_report.outputs.latest_report }}/
      - name: "Upload Test Reports Artifacts"
        if: always()
        uses: "actions/upload-artifact@v6"
        with:
          name: gdunit-reports
          path: reports/**
          retention-days: 5
      - name: "Install Codecov CLI"
        if: success()  # Only if tests pass.
        run: |
          curl -Os https://cli.codecov.io/latest/linux/codecov
          chmod +x codecov
      - name: "Upload Test Report to Codecov"  # Last step for uploading JUnit XML as test report
        if: success()  # Only if tests pass.
        run: |
          ./codecov upload-process --token ${{ secrets.CODECOV_TOKEN }} ${{ steps.find_report.outputs.latest_report }}//test-report.xml --name "GDUnit4 Test Report" --flag GDUnit4 --report-type test_results
