---
name: "Release Drafter PR Updates"

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: ["opened", "reopened", "synchronize", "edited"]  # Same types

permissions:
  contents: "read"

jobs:
  update_release_draft:
    permissions:
      contents: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      # yamllint disable-line rule:line-length
      - uses: "release-drafter/release-drafter@6db134d15f3909ccc9eefd369f02bd1e9cffdf97"  # v6.2.0
        with:
          config-name: "release-drafter.yml"  # Your existing config
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
