---
name: "Yamllint"

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      config-path:
        description: "A folder name to run tests on"
        required: true
        type: "string"

permissions:
  contents: "read"
  pull-requests: "read"

jobs:
  build:
    runs-on: "ubuntu-24.04"
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - uses: "actions/checkout@v6.0.1"
      - name: "Cache PIP Dependencies"
        uses: "actions/cache@v5"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-yamllint"
          restore-keys: |
            ${{ runner.os }}-pip-
        # yamllint disable rule:line-length
      - name: Set up Python ${{ matrix.python-version }}  # yamllint disable-line rule:quoted-strings
        # yamllint enable rule:line-length
        uses: "actions/setup-python@v6"
        with:
          python-version: "${{ matrix.python-version }}"
      # You can test your matrix by printing the current Python version
      - name: "Display Python Version"
        run: |
          python -c "import sys; print(sys.version)"
      - name: "Install Yamllint"
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade yamllint
      - name: "Version Check"
        run: |
          python -m yamllint --version

      - name: "Analysing YML Files"
        run: |
          python -m yamllint -c .yamllint.yaml ${{ inputs.config-path }}
